export let template = `
from .colors import *
from .fonts import *
from .structure import *

# Text
token_text_color_default = color_general_white
token_text_color_default_inverted = color_general_black

token_text_color_isaac_disabled = color_gray_45
token_text_color_custom_disabled = color_gray_64
token_text_color_custom_pressed = color_gray_45

token_text_color_secondary = color_gray_58

# Buttons
token_button_radius = structure_radius_default
token_button_padding = structure_padding_default

token_buttons_primary_default = color_green_60_35
token_buttons_primary_hover = color_green_43_52
token_buttons_primary_pressed = color_green_80_26
token_buttons_primary_checked = color_green_51_27
token_buttons_primary_disabled = color_green_51_27

token_buttons_secondary_default = color_blue_60_35
token_buttons_secondary_hover = color_blue_43_52
token_buttons_secondary_pressed = color_blue_80_26
token_buttons_secondary_checked = color_blue_51_27
token_buttons_secondary_disabled = color_blue_51_27

token_buttons_warning_default = color_orange_60_35
token_buttons_warning_hover = color_orange_43_52
token_buttons_warning_pressed = color_orange_80_26
token_buttons_warning_checked = color_orange_51_27
token_buttons_warning_disabled = color_orange_51_27

token_buttons_danger_default = color_red_60_35
token_buttons_danger_hover = color_red_43_52
token_buttons_danger_pressed = color_red_80_26
token_buttons_danger_checked = color_red_51_27
token_buttons_danger_disabled = color_red_51_27

token_buttons_normal_default = color_gray_21
token_buttons_normal_hover = color_gray_45
token_buttons_normal_pressed = color_gray_27
token_buttons_normal_checked = color_gray_05
token_buttons_normal_disabled = color_gray_05

# Radio Buttons
token_radiobuttons_normal_default = color_gray_21
token_radiobuttons_normal_hover = color_gray_45
token_radiobuttons_normal_pressed = color_gray_27
token_radiobuttons_normal_disabled = color_gray_05

# Combobox
token_combobox_radius = structure_radius_default
token_combobox_padding = structure_radding_default

token_combobox_secondary_default = color_blue_51_27
token_combobox_secondary_hover = color_blue_43_52
token_combobox_secondary_pressed = color_blue_80_26
token_combobox_secondary_disabled = color_gray_45

# Demonstration Outcomes
token_demonstration_outcome_success = color_green_43_52
token_demonstration_outcome_success_with_corrections = color_blue_43_52
token_demonstration_outcome_failed = color_orange_43_52
token_demonstration_outcome_mark_for_deletion = color_red_43_52

# Fonts
token_font_size_default = font_size_sm

token_font_size_h1 = font_size_xxl
token_font_size_h2 = font_size_xl
token_font_size_h3 = font_size_lg
token_font_size_h4 = font_size_md

token_font_size_sm = font_size_sm
token_font_size_xs = font_size_xs
`